### ISSUE TITLE
PyModule_AddObjectRef breaks Python 3.9 builds (Debian bullseye, RHEL/EL 9)

### ISSUE THREAD

**Issue by nomike** [pythonscad/pythonscad#617]
## Summary

Manually-triggered runs of `build-debian-packages.yml` and `build-rpm-packages.yml` against PR #614 fail in the **bullseye / amd64** and **el 9 / amd64** matrix entries with:

```
src/python/pyopenscad.cc:1585:7: error: 'PyModule_AddObjectRef' was not declared in this scope; did you mean 'PyModule_AddObject'?
src/python/pyopenscad.cc:1589:7: error: ...
src/python/pyopenscad.cc:1593:7: error: ...
```

`PyModule_AddObjectRef` is part of the [Python 3.10 C API](https://docs.python.org/3/c-api/module.html#c.PyModule_AddObjectRef). Debian bullseye and RHEL/EL 9 ship Python **3.9**, where the symbol doesn't exist, so the build fails at link time on those distros.

## Affected runs

- Debian bullseye amd64: https://github.com/pythonscad/pythonscad/actions/runs/25312022583/job/74200913804
- RPM el 9 amd64: https://github.com/pythonscad/pythonscad/actions/runs/25312023860/job/74200917774

## Root cause

Introduced by #579 (`feat(python)!: introduce _openscad / openscad / pythonscad three-module layout`), commit 542c89eaa. Last green run on `v0.20.0` (run 24426642976) was on 2026-04-14 — bullseye and el9 both passed there, so the regression sits squarely between `v0.20.0` and current master.

## Why this is a master-side bug, not a PR-#614 regression

PR #614 only touches CI workflows (`.github/workflows/*.yml`), `.github/zizmor.yml`, and `.pre-commit-config.yaml`. It doesn't touch `src/python/`. The same compile failure will hit master directly the next time `build-debian-packages.yml` / `build-rpm-packages.yml` run.

## Suggested fix

One of:

1. Use the [Python 3.9-compatible `Py_NewRef` + `PyModule_AddObject` pattern](https://docs.python.org/3/c-api/module.html#c.PyModule_AddObject) instead of `PyModule_AddObjectRef`.
2. Bump the minimum required Python to 3.10 and drop bullseye / el 9 from the build matrix.
3. Conditionally compile: `#if PY_VERSION_HEX >= 0x030A0000 PyModule_AddObjectRef(...) #else PyModule_AddObject(...) #endif` — note the reference-counting semantics differ slightly.

Option 1 is probably the lowest-risk; it keeps the existing matrix and just shifts the call to a cross-version symbol.
